rules = [
  OrganizeImports,
]

OrganizeImports {
  coalesceToWildcardImportThreshold = 40
  expandRelative = false
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Merge

  groups = [
    "java.util.", "java.time.", "java.sql", "java.text.",
    "re:javax?\\.",
    "org.slf4j.",
    "scala.language", "scala.util", "scala.collection", "scala.",
    "*",
    "org.specs2.",
    "org.scalacheck.",
    "_root_.",
    "test"
  ]

  importSelectorsOrder = SymbolsFirst
  importsOrder = SymbolsFirst
  removeUnused = true
}
